### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/saved_dict/bert.ckpt'

### ISSUE THREAD

**Issue by ppkk1993** [HoyTta0/KnowledgeDistillation#1]
运行文件不太行 = =

**Comment by HoyTta0** [comment]
在data文件夹下创建saved_dict目录就行了，这个目录下存的是模型参数

**Comment by ppkk1993** [comment]
> 在data文件夹下创建saved_dict目录就行了，这个目录下存的是模型参数

还是不行，我加入胡文星那个git训练的ckpt提示torchsize对应不上，你这个是192，他的是10。。现在都蒙了，大佬能写个食用说明吗?我看了看代码是直接运行python distill.py

**Comment by HoyTta0** [comment]
这里存放的是教师模型训练好的参数，需要训练得到，不是bert预训练模型的参数，我写个使用说明吧。有几个文件太大了我没传上来。

**Comment by HoyTta0** [comment]
所需要下载的文件以及放置的路径已经更新在README里面。
