### ISSUE TITLE
运行distill.py遇到问题

### ISSUE THREAD

**Issue by pikapi111** [HoyTta0/KnowledgeDistillation#10]
您好，运行的时候碰到这个问题
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument target in method wrapper_nll_loss_forward)
是因为有的参数在cpu有的在gpu上吗？请问那些地方需要更改一下？

**Comment by HoyTta0** [comment]
你好，请提供一下完整的报错信息

**Comment by HoyTta0** [comment]
在teacher.py的teacher_train以及teacher_evaluate函数中添加
`labels = labels.to(config.device)`
感谢指出🙏

**Comment by pikapi111** [comment]
感谢解答，已成功运行
