### ISSUE TITLE
您好，请问方便分享textgcn的源码吗

### ISSUE THREAD

**Issue by Changanyue** [HoyTta0/KnowledgeDistillation#5]

**Comment by HoyTta0** [comment]
请提供一下邮箱

**Comment by Changanyue** [comment]
***@***.***&nbsp; 感谢
 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月10日 11:09:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HoyTta0/KnowledgeDistillation] 您好，请问方便分享textgcn的源码吗 (#5)




 
请提供一下邮箱
