### ISSUE TITLE
项目错误

### ISSUE THREAD

**Issue by lyk595** [HoyTta0/KnowledgeDistillation#7]
你好，我在运行你的项目knowledge distillation时遇到了一个错误：FileNotFoundError: [Errno 2] No such file or directory: 'sgns.wiki.word'。请问该怎么解决？

**Comment by HoyTta0** [comment]
请参考README使用说明

**Comment by lyk595** [comment]
您好，我有按照readme的操作，下载数据集，创建文件夹，但是仍然报错。麻烦看一下图片截图







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HoyTta0/KnowledgeDistillation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HoyTta0/KnowledgeDistillation] 项目错误 (#7)





 
请参考README使用说明
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HoyTta0** [comment]
版本已更新，现在不需要下载'sgns.wiki.word'就可以使用
